repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: end-of-file-fixer
        -   id: check-yaml
  -   repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        -   id: flake8
  -   repo: https://github.com/hhatto/autopep8
      rev: v2.0.4
      hooks:
        -   id: autopep8
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
        -   id: pyupgrade
            args: [--py310-plus]
